#!/usr/bin/env python3
"""重新标定金标准登记表(tests/golden.json)。

登记表是夹具的**认证值**。SPEC(下方)是人工权威来源:每个夹具的数据源、
已知真值(生成参数)、说明与容差;`reading`/`groups` 由本脚本从冻结的
夹具字节实测计算并写入——不手工编辑。

**重定标流程**(算法有意变更后):
1. 运行本脚本 → 重算读数写回 golden.json;
2. `git diff tests/golden.json` → 逐夹具看清读数漂移了多少(这就是留痕);
3. commit 里写明「重定标:读数整体 ±N%,因为改了 X」。
真值不变,故 diff 只动 reading——一眼看出基准挪了多少。测试的「读数 vs 真值」
校准断言仍会拦截**有偏的重定标**(改完把读数标定到错的地方)。

容差:
- drift_tol —— 读数 vs 登记值:紧,同码确定性输出,任何真实算法变更都会越界;
- calib_tol —— 读数 vs 真值:估计器无偏性的书面保证,越界=估计器有偏。
"""
import importlib.util
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
FIX = os.path.join(HERE, "fixtures")

# 人工权威来源:改标准从这里改(以及 gen_fixtures.py 的原始字节)
METRIC_VERSION = "1.2"
DRIFT_TOL = {"tps": 0.5, "ttft": 0.2}
CALIB_TOL = {"tps_rel": 0.03, "ttft_abs": 0.5}
SPEC = [
    ("claude-steady-70x5", "claude", (70.0, 5.0),
     "Claude 主标定:6 条稳态响应,真值 TPS=70 TTFT=5s"),
    ("claude-steady-45x8", "claude", (45.0, 8.0),
     "第二档速率:验证估计器在不同 regime 都无偏"),
    ("claude-noisy-70x5", "claude", (70.0, 5.0),
     "带确定性噪声:非完美线性,读数对稳健估计器内部改动敏感"),
    ("claude-fallback-lowerbound", "claude", None,
     "下界回退路径:仅 3 条长回复,读数=(blended 中位, None)"),
    ("claude-mixed-model", "claude", (70.0, 5.0),
     "分模型过滤:opus 段+fable 段,读数应=当前 fable 模型"),
    ("codex-steady-90x4", "codex", (90.0, 4.0),
     "Codex 主标定:真值 TPS=90 TTFT=4s"),
    ("codex-instant-group", "codex", (90.0, 4.0),
     "病理:瞬时组(毫秒时间戳簇)被 plausible_point 过快界过滤,读数落回真值"),
    ("codex-cross-turn", "codex", (90.0, 4.0),
     "病理:未收尾轮在边界丢弃,不与下轮合并,读数落回真值"),
    ("kimi-steady-80x6", "kimi", (80.0, 6.0),
     "Kimi 主标定:6 条稳态响应,真值 TPS=80 TTFT=6s"),
    ("kimi-retry", "kimi", (80.0, 6.0),
     "病理:失败请求无 step.end,锚点取重试的 llm.request,读数落回真值"),
    ("opencode-steady-85x5", "opencode", (85.0, 5.0),
     "OpenCode 主标定:6 条稳态响应,out=output+reasoning,真值 TPS=85 TTFT=5s"),
    ("opencode-tool-time", "opencode", (85.0, 5.0),
     "病理:扣除前序工具执行区间,以最后 tool start 为生成边界,读数落回真值"),
]


def opencode_groups(cs, lines):
    """归一化 JSONL 按 SQLite 来源表拆开后交给 OpenCode 解析器。"""
    records = [json.loads(line) for line in lines]
    messages = [r for r in records if r.get("table") == "message"]
    parts = [r for r in records if r.get("table") == "part"]
    return cs.opencode_parse(messages, parts)[0]


PARSERS = {"claude": lambda cs, lines: cs.response_groups(lines)[0],
           "codex": lambda cs, lines: cs.codex_parse(lines)[0],
           "kimi": lambda cs, lines: cs.kimi_parse(lines)[0],
           "opencode": opencode_groups}


def load_cs():
    spec = importlib.util.spec_from_file_location("cs", os.path.join(REPO, "collect.py"))
    m = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(m)
    return m


def measure(cs, name, source):
    """读冻结夹具 → 解析 → 当前模型组 → fit_speed。返回 (groups数, reading)。"""
    lines = open(os.path.join(FIX, name + ".jsonl")).read().splitlines()
    groups = PARSERS[source](cs, lines)
    fit = cs.fit_speed(cs.current_model_groups(groups))
    if fit is None:
        reading = None
    elif fit[1] is None:
        reading = {"tps": round(fit[0], 3), "ttft": None}
    else:
        reading = {"tps": round(fit[0], 3), "ttft": round(fit[1], 3)}
    return len(groups), reading


def main():
    cs = load_cs()
    fixtures = {}
    for name, source, truth, note in SPEC:
        n, reading = measure(cs, name, source)
        fixtures[name] = {
            "source": source, "note": note,
            "truth": ({"tps": truth[0], "ttft": truth[1]} if truth else None),
            "groups": n, "reading": reading,
        }
    doc = {
        "metric_version": METRIC_VERSION,
        "_note": "machine-generated by tests/regen_golden.py — do not hand-edit; see METRIC.md",
        "drift_tol": DRIFT_TOL, "calib_tol": CALIB_TOL,
        "fixtures": fixtures,
    }
    with open(os.path.join(HERE, "golden.json"), "w") as f:
        json.dump(doc, f, ensure_ascii=False, indent=2)
        f.write("\n")
    print("wrote golden.json (%d fixtures, metric v%s)" % (len(fixtures), METRIC_VERSION))
    for name, e in fixtures.items():
        print("  %-28s %s" % (name, e["reading"]))


if __name__ == "__main__":
    main()
